import argparse
import csv
import logging
from pathlib import Path
import sys

import pandas as pd


def main() -> None:
    """Assign consensus taxonomy to each phylotype from per-SV taxonomic annotations."""
    args_parser = argparse.ArgumentParser(
        description="""Find the consensus species (or best effort) for a given phylotype
        when you have a per-sequence variant taxonomic output (as from MaLiAmPi)
        """
    )
    args_parser.add_argument(
        "--phylotypes",
        "-p",
        help="CSV file with two columns: phylotype and sv. Represents the phylotype to sequence variant mapping",
        required=True,
    )
    args_parser.add_argument(
        "--taxonomy",
        "-t",
        help="CSV file with per SV taxonomic assignments in long format (as generated by MaLiAmPi)",
        required=True,
    )
    args_parser.add_argument(
        "--out",
        "-O",
        help="Output of phylotype <-> species mapping. CSV format with header of phylotype and species",
        type=Path,
        required=True,
    )
    args = args_parser.parse_args()

    logging.info("Loading SV-taxonomy in long format")
    sv_tax = pd.read_csv(args.taxonomy).rename({"name": "sv"}, axis=1)
    for col in ("sv", "want_rank", "rank", "tax_name"):
        if col not in sv_tax.columns:
            logging.error("Taxonomy is missing a '%s' column. Perhaps it is not in the correct format", col)
            sys.exit(-1)

    logging.info("Loading phylotype <-> SV mapping")
    pt_sv_df = pd.read_csv(args.phylotypes)
    for col in ("phylotype", "sv"):
        if col not in pt_sv_df.columns:
            logging.error("Phylotype input is missing a '%s' column. Perhaps it is in the incorrect format", col)
            sys.exit(-1)

    sv_pt = {r.sv: r.phylotype for (i, r) in pt_sv_df.iterrows()}
    # Cache all the phylotypes we are trying to name...
    all_pt = set(sv_pt.values())

    # Add the phylotype assignment to the taxonomy table
    sv_tax["phylotype"] = sv_tax.sv.apply(sv_pt.get)

    logging.info("Attempting to find a species-level taxon for each phylotype")
    # First try for species-level via majority rules
    pt_sp = {
        pt: r.tax_name
        for pt, r in sv_tax[sv_tax["rank"] == "species"][["phylotype", "tax_name"]]
        .groupby("phylotype")
        .value_counts()
        .reset_index()
        .groupby("phylotype")
        .first()
        .iterrows()
    }
    # Find the remainder
    pt_no_sp = all_pt - set(pt_sp.keys())

    logging.info("There are %d out of %d phylotypes without a species-level taxon.", len(pt_no_sp), len(all_pt))
    # ... and do our best, noting it is not a species-level annotation by appending ' spp.'
    pt_sp.update(
        {
            pt: f"{r.tax_name} spp."
            for pt, r in sv_tax[(sv_tax.want_rank == "species") & (sv_tax.phylotype.apply(lambda pt: pt in pt_no_sp))][
                ["phylotype", "tax_name"]
            ]
            .groupby("phylotype")
            .value_counts()
            .reset_index()
            .groupby("phylotype")
            .first()
            .iterrows()
        }
    )

    logging.info("There were %d phylotypes without any taxonomic annotation", len(all_pt - set(pt_sp.keys())))
    logging.info("Writing output")
    with args.out.open("w") as out_fh:
        out_w = csv.DictWriter(out_fh, fieldnames=["phylotype", "species"])
        out_w.writeheader()
        out_w.writerows([{"phylotype": k, "species": v} for (k, v) in pt_sp.items()])
    logging.info("Done.")


if __name__ == "__main__":
    main()
